name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # SourceTreeでメインに使っているブランチ名（masterの場合はここをmasterに変えてください）

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: |
          cd bakusatsu
          flutter pub get

      - name: Build Web
        # ここでリポジトリ名を指定しています
        run: |
          cd bakusatsu
          flutter build web --release --base-href "/bakusatsuRegenerate/"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./bakusatsu/build/web